# Generated by Django 3.2 on 2023-05-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название отеля')),
                ('image', models.ImageField(upload_to='hotels/%Y/%m/%d', verbose_name='Изображение отеля')),
                ('description', models.CharField(max_length=255, verbose_name='Описание отеля')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название новости')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='Изображение новости')),
                ('description', models.CharField(max_length=255, verbose_name='Описание новости')),
                ('backround', models.ImageField(blank=True, upload_to='bg/%Y/%m/%d', verbose_name='Фон главного экрана')),
                ('detailed_desc', models.CharField(default=0, max_length=1000, verbose_name='Подробное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Страна')),
                ('second_name', models.CharField(default=0, max_length=120, verbose_name='Название тура')),
                ('image', models.ImageField(blank=True, upload_to='tour/%Y/%m/%d', verbose_name='Изображение')),
                ('backround', models.ImageField(blank=True, upload_to='bg/%Y/%m/%d', verbose_name='Фон главного экрана')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('conditions', models.TextField(verbose_name='Условия тура')),
                ('hotels', models.ManyToManyField(to='mainapp.Hotels', verbose_name='Отели')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour', verbose_name='Выберите страну')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
    ]
