# Generated by Django 3.2 on 2023-06-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230619_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='select',
        ),
    ]
