# Generated by Django 3.2 on 2023-06-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_feedback_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='select',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour', verbose_name='Выберите страну'),
        ),
    ]
