# Generated by Django 3.2 on 2023-06-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_feedback_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=256, verbose_name='Имя'),
        ),
    ]
